services:
  mysql:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql
    ports:
      - 3306:3306
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 60s
      retries: 10

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
  redis-data: