component_management:
  individual_components:
    - component_id: users
      path:
        - cmd/shauser/**
    - component_id: content
      path:
        - sharp/**
ignore:
  - sharp/content/Program.cs