openapi: "3.0.3"
info:
  title: "sharing_comment API"
  description: "sharing_comment API"
  version: "1.0.0"
servers:
  - url: "https://sharing_comment"
paths:
  /comments/main:
    get:
      summary: "GET comments/main"
      operationId: "getMainCommentList"
      parameters:
        - name: "belong_to"
          in: "query"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "page"
          in: "query"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "size"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "10"
        - name: "Authorization"
          in: "header"
          required: false
          schema:
            type: "string"
            default: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Comment"
  /comments/reply:
    get:
      summary: "GET comments/reply"
      operationId: "getReplyCommentList"
      parameters:
        - name: "reply_to"
          in: "query"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "page"
          in: "query"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "size"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "10"
        - name: "Authorization"
          in: "header"
          required: false
          schema:
            type: "string"
            default: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Comment"
  /comments:
    post:
      summary: "POST comments"
      operationId: "createComment"
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommentRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Comment"
  /comments/{id}:
    delete:
      summary: "DELETE comments/{id}"
      operationId: "deleteComment"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommentRequest"
        required: true
      responses:
        "200":
          description: "OK"
  /comments/action/like/{id}:
    post:
      summary: "POST comments/action/like/{id}"
      operationId: "voteComment"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
    delete:
      summary: "DELETE comments/action/like/{id}"
      operationId: "cancelVoteComment"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
components:
  schemas:
    User:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        is_follow:
          type: "boolean"
        avatar_url:
          type: "string"
        bg_url:
          type: "string"
        bio:
          type: "string"
        likes_given:
          type: "integer"
          format: "int32"
        likes_received:
          type: "integer"
          format: "int32"
        videos_posted:
          type: "integer"
          format: "int32"
        following:
          type: "integer"
          format: "int32"
        followers:
          type: "integer"
          format: "int32"
    Comment:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        user_id:
          type: "integer"
          format: "int64"
        content:
          type: "string"
        reply_to:
          type: "integer"
          format: "int64"
        belong_to:
          type: "integer"
          format: "int64"
        created_at:
          type: "string"
          format: "date-time"
        reply_count:
          type: "integer"
          format: "int32"
        like_count:
          type: "integer"
          format: "int32"
        reply_comments:
          type: "array"
          items:
            $ref: "#/components/schemas/Comment"
        voted:
          type: "boolean"
        user:
          $ref: "#/components/schemas/User"
    CommentRequest:
      type: "object"
      properties:
        content:
          type: "string"
        reply_to:
          type: "integer"
          format: "int64"
        belong_to:
          type: "integer"
          format: "int64"