spring:
  threads:
    virtual:
      enabled: true
  datasource:
    username: ${DB_USER:v1}
    password: ${DB_PASSWORD:ABCDEF}
    url: jdbc:mysql://${DB_HOST:db}:${DB_PORT:3306}/${DB_NAME:comments}?${DB_OPTIONS:useSSL=false&serverTimezone=UTC}
    driver-class-name: com.mysql.cj.jdbc.Driver