ListenOn: :8089
VideoService:
  Address: shavideo:8082
SECRET: $JWT_SECRET
ImageBucket: $IMAGE_BUCKET
VideoBucket: $VIDEO_BUCKET
MINIO:
  Endpoint: string
  AccessKey: string
  SecretKey: string
  UseSSL: bool
