ListenOn: :8080
MySQL:
  DSN: mysql_user:mysql@tcp(localhost:3306)/users?charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true
  Replicas: [ ] # support multiple mysql replicas dsn
DefaultLimit: 20
MaxLimit: 100
Secret: "this is a secret"