name: CI
on:
  push:
    branches:
      - '*'
    tags:
      - ''
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm' # See 'Options' for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: AOT Compilation
        run: |
            mvn -q -Pnative compile -DskipTests
            mvn -q -Pnative spring-boot:process-aot -DskipTests
      - name: docker-compose up
        run: docker-compose up -d
      - name: Unit Test
        run: |
          mvn -q clean
          mvn -q test
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: db
          DB_USER: v1
          DB_PASSWORD: ABCDEF
          DB_OPTIONS: useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          TRACING_PROBABILITY: 0.1
          OTLP_ENDPOINT: http://localhost:4318/v1/traces
          VOTE_SERVICE_BASE_URL: http://localhost:8081
          USER_SERVICE_BASE_URL: http://localhost:5000
          REDIS_HOST: localhost
          SERVICE_VOTE_ENABLED: false

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm' # See 'Options' for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Native Image Build
        run: mvn -Pnative spring-boot:build-image -DskipTests

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker tag sharing-comment:0.0.1-SNAPSHOT ${{ secrets.DOCKERHUB_USERNAME }}/sharing-comment:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sharing-comment:latest