name: followapi-ci
# work on path /cmd/followapi
on:
  push:
    paths:
      - 'cmd/followapi/**'
      - '.github/workflows/followapi-ci.yaml'
    branches:
      - main
  pull_request:
    paths:
      - 'cmd/followapi/**'
      - '.github/workflows/followapi-ci.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build followapi Binary Executable
        run: |
          go mod tidy
          cd cmd/followapi
          go mod tidy
          go build -ldflags="-s -w" -o followapi